name = "proyecto-catalogo"
compatibility_date = "2025-10-30"

[[d1_databases]]
binding = "DB"
database_name = "catalogo-db"
database_id = "05362644-3ef3-4d00-8a7b-9453a2966026"

migrations_dir = "drizzle/migrations"
